### ISSUE TITLE
Indentation skips colon character in previous line

### ISSUE THREAD

**Issue by pjantrania** [mmcjimsey26/yuck-mode#3]
It looks like the indentation for each line increases by one space if the first non-whitespace character of the previous line is a colon (or maybe any special character). Here's an example:
```
(defwindow example
	   :monitor 0
	    :geometry (geometry :x "0%"
				 :y "20px"
				  :width "90%"
				   :height "30px"
				    :anchor "top center")
	     :stacking "fg"
	      #foo bar
	       baz
	       :reserve)
```
Is there a simple way to customize this behavior, or would it require a change in how the indent function works?
My emacs-version is
GNU Emacs 29.0.60 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6) of 2022-12-07

**Comment by mmcjimsey26** [comment]
It seems that it might be an issue with `lisp-indent-line`. I'll see what I can do.

**Comment by mmcjimsey26** [comment]
Resolved in https://github.com/mmcjimsey26/yuck-mode/commit/e084416fa3e7f91bb429edbf7ff1585aa5674367

**Comment by pjantrania** [comment]
I pulled the change and indentation works as expected. thanks @mmcjimsey26 for the quick and informative fix!
